buttons-base style
ErazorWhite/goit-75-8-Mimino pull request #16
Opened 2023-01-30 15:06 UTC by Lilia-Pogosova

Базові стилі на кнопки для ваших секцій

2023-01-30 16:36 UTC, ErazorWhite requested changes
Много кода повторяется. 
Тот же border-radius: 25px; ты написала аж пять раз.
Вспомни приём из школьной математики - вынести за скобки.
Создай общий родительский класс кнопки и вынеси туда повторяющиеся значения.
Потом родительский класс кнопки добавь в дочерние при помощи директивы @extend

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +        line-height: 20px;
20 / 16 = 1.25
треба скорегувати line-height: 20px;

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +    line-height: 24px;
треба позбавлятися пікселів у line-height як вище зазначив

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +                line-height: 29px;
треба позбавлятися пікселів у line-height як вище зазначив

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +.btn-txt{
пропоную перенести у класс btn та зробити через вкладенність sass
тобно не .btn-txt, а &-txt

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +    width: 236px;
не потрібно задавати фіксовану ширину кнопкам, бо вони не пройдуть тести на стресостійкість через переповнення текстом. Юзай min-width або max-width

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +    width: 298px;
не потрібно задавати фіксовану ширину кнопкам, бо вони не пройдуть тести на стресостійкість через переповнення текстом. Юзай min-width або max-width

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +                    width: 434px;
не потрібно задавати фіксовану ширину кнопкам, бо вони не пройдуть тести на стресостійкість через переповнення текстом. Юзай min-width або max-width

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +    width: 384px;
не потрібно задавати фіксовану ширину кнопкам, бо вони не пройдуть тести на стресостійкість через переповнення текстом. Юзай min-width або max-width

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +                    width: 592px;
![image](https://user-images.githubusercontent.com/41112771/215535098-052b5e89-67d0-4adb-8b9f-9ce9ccdf84ae.png)

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +    width: 384px;
![image](https://user-images.githubusercontent.com/41112771/215535152-e98da22e-1457-4bc4-9146-7be8b761db34.png)

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +    width: 298px;
![image](https://user-images.githubusercontent.com/41112771/215535217-70d4cf98-9888-4cbe-8942-1a915cbfca40.png)

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +    width: 236px;
![image](https://user-images.githubusercontent.com/41112771/215535232-ea5ae689-c855-4a71-88bb-e0d19897885e.png)

2023-01-30 16:36 UTC, ErazorWhite commented on src/sass/components/_buttons.scss
> +.btn-type{
пропоную перенести у класс btn та зробити через вкладенність sass
тобно не .btn-txt, а &-type

2023-01-31 06:36 UTC, Lilia-Pogosova commented on src/sass/components/_buttons.scss
> +.btn-make-reserv-txt{
просто це різні кнопки зовсім. навіщо робити через вкладеності?

2023-01-31 19:49 UTC, SerhiiFrolikov approved these changes

2023-02-01 18:45 UTC, merged