Feature/section  lux
ErazorWhite/goit-75-8-Mimino pull request #3
Opened 2023-01-28 18:50 UTC by TatarskikoT

2023-01-29 08:55 UTC, Valerii69 approved these changes

2023-01-29 09:53 UTC, ErazorWhite commented
Не використав вкладенність sscc коду.
У тебе все у стовпчик написано: https://github.com/ErazorWhite/goit-75-8-Mimino/blob/feature/section__lux/src/sass/pages/hotel/_1r_2ad_luxe.scss
А треба оссь так: https://github.com/ErazorWhite/goit-markup-hw-08/blob/main/sass/pages/studio/_product.scss

2023-01-29 10:41 UTC, ErazorWhite requested changes
Не використав вкладенність sscc коду.
У тебе все у стовпчик написано: https://github.com/ErazorWhite/goit-75-8-Mimino/blob/feature/section__lux/src/sass/pages/hotel/_1r_2ad_luxe.scss
А треба оссь так: https://github.com/ErazorWhite/goit-markup-hw-08/blob/main/sass/pages/studio/_product.scss

2023-01-29 12:11 UTC, mashanstrk requested changes

2023-01-31 03:31 UTC, Valerii69 approved these changes

2023-02-02 19:46 UTC, merged

2023-02-03 18:55 UTC, TatarskikoT commented on src/partials/hotel/1r_2ad_luxe.html
> +        <p class="lux__brand-name">Mimiho</p>
So... Mimino or MIMIHO?