Origin/contacts
ErazorWhite/goit-75-8-Mimino pull request #5
Opened 2023-01-29 08:34 UTC by Valerii69

2023-01-29 11:09 UTC, ErazorWhite requested changes
Три моменти
1. Шрифти видали в себе локально, юзай ті що ми додали через гілку main. Якщо я змерджу твою гілку, то будуть конфлікти.
2. В тебе якийсь жах з форматуванням відбуваеться у файлі _contakts.scss, перевіряти важко. Будь ласка встанови до VScode "SCSS Formatter v2.4.4" та відформатуй весь scss код за допомогою плагіна.
3. У файлі _contakts.scss ти занадто часто повторюешь "contacts__". Заміни у вкладенних класів текст оголошення на "&__"
4. В англійскій мові правильно не "contakts", а "contacts". Тому зміни назву файлу.

2023-02-01 14:56 UTC, AlessioItaliano requested changes

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +    @media screen and (min-width: 414px) and (max-width: 1023px) {
Цього маржина не потрібно у вас флекс є на contacts__block він дає відступ. Інакше з цим маржином воно ламає верстку на мобільній версіі.

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +    margin-right: 10px;
по макету  маржин на телефонах 8рх, а та голці 10

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +    &--hotel {
тут чисто моя думка , що вартує падінги зробити для двох номерів по 6рх між ними а не 12 , осккільки получається що лівий номер вперається в правий і в нього більше поле натискання.

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +    background: $primaryLight;
не той background, у вас #fffdee а має бути #FFFFFF

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +    width: 260px;
повторяється ширина і вифота загальному і мобільному блоці, одну можна видалити

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +        padding: 10px;
на мобільному верхній і нижній падінг 8 і 7 ,а не 10рх

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +    box-sizing: border-box;
box-sizing: border-box повторюєте стиль який приходить від модерн нормалайз

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +    @media screen and (min-width: 1280px) {
Стиль повністю повторює стиль таблета, тому можна видалити це,  залишивши @media screen and (min-width: 1024px) без максу

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +        @media screen and (min-width: 1280px) {
Тут також повторення стилів таблета і декстопа

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +        width: 260px;
карта трохи зїжає в право , можна добавити 2рх до ширини щоб її вирівняти з телефонами

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +    @media screen and (min-width: 1280px) {
повторення стилів на таблеті та лдекстопі , можна лишити лиш таблет бе максу

2023-02-01 14:56 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakts.scss
> +        flex-direction: row;
Аналогічне повторення стилів таблет і дектоп

2023-02-02 14:05 UTC, AlessioItaliano commented on src/sass/pages/main_page/_contakt.scss
> +
За макетом колір білий , у вас загальний фон получається зі всім. візьміть останні обновлення , там у змінних є білий колір

2023-02-02 14:21 UTC, AlessioItaliano approved these changes

2023-02-02 14:31 UTC, Valerii69 commented
Доробив. Монітор, падлюка, не так передавав color

чт, 2 февр. 2023 г. в 16:05, Vasyl Lepish ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/sass/pages/main_page/_contakt.scss
> <https://github.com/ErazorWhite/goit-75-8-Mimino/pull/5#discussion_r1094574817>
> :
>
> > +
>
> +    &--hotel {
>
> +        justify-content: space-between;
>
> +        @media screen and (min-width: 1024px) {
>
> +            margin-bottom: 48px;
>
> +        }
>
> +    }
>
> +
>
> +    &__item {
>
> +        display: flex;
>
> +        box-sizing: border-box;
>
> +        flex-wrap: wrap;
>
> +        align-items: center;
>
> +        justify-content: center;
>
> +        background: $primaryLight;
>
> +
>
>
> За макетом колір білий , у вас загальний фон получається зі всім. візьміть
> останні обновлення , там у змінних є білий колір
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ErazorWhite/goit-75-8-Mimino/pull/5#pullrequestreview-1281123016>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4A6U7MBIF3H5HQZHZGR3BDWVO5KHANCNFSM6AAAAAAUKDYOEA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-02 21:26 UTC, merged